services:

    # filemaker.database:
    #     class: filemakerBundle\services\filemakerservice
    #     arguments: [@service_container]

    # filemaker.database_v2:
    #     class: filemakerBundle\services\filemakerservice_v2
    #     arguments: [@service_container]

    # filemakermin.database:
    #     class: filemakerBundle\services\filemakerservicemin
    #     arguments: [@service_container]

