services:
#    filemaker.example:
#        class: filemakerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    filemaker.database:
        class: filemakerBundle\services\filemaker
        arguments: [@service_container]